### ISSUE TITLE
本地运行开发 启动的问题？ 

### ISSUE THREAD

**Issue by jjeejj** [NaoTu/DesktopNaotu#28]
按照 /doc/Dev.md 文档中， 执行命令安装一些 gulp 插件，并且执行 npm i 安装一些其他的依赖后
执行 npm start ,一只在报错，启动不来

> desktopnaotu@1.0.3 start /Users/jiang/Repo/DesktopNaotu
> gulp default && electron main.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jiang/Repo/DesktopNaotu/node_modules/gulp-babel/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jiang/Repo/DesktopNaotu/gulpfile.js:22:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)

这怎么解决呢？是不是少了一些东西呢。

**Comment by topcss** [comment]
我想，你需要补充添加 @babel/core ，要用 npm 来安装。

**Comment by jjeejj** [comment]
@topcss  好吧  其实尝试过了， 昨天晚上怎么安装都不行的。今天突然就好了。那就关了了。。。
